# Generated by Django 4.2.30 on 2026-06-28 13:57

from django.db import migrations, models
import django.db.models.deletion
import quizapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_name', models.CharField(max_length=64)),
                ('code', models.CharField(default=quizapp.models.quiz_code_generator, max_length=8, unique=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('latest_updated_date', models.DateTimeField(auto_now=True, verbose_name='date when latest updated')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=256)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('latest_updated_date', models.DateTimeField(auto_now=True, verbose_name='date when latest updated')),
                ('quiz_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.quizinstance')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=256)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.question')),
            ],
        ),
    ]
