# Generated by Django 4.2.30 on 2026-06-29 13:33

from django.db import migrations, models
import quizapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_alter_choice_id_alter_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizinstance',
            name='quiz_title',
            field=models.CharField(default=models.CharField(default=quizapp.models.quiz_code_generator, max_length=8, unique=True), max_length=64),
        ),
    ]
